name: build-master
on: [pull_request, push]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17 # Run on Java 17
        ]
        os: [
          ubuntu-latest # Run on latest version of Ubuntu
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          job-id: ${{ matrix.java }}
          arguments: build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Build Artifacts
          path: build/libs
